[2022-03-24 18:45:46,314] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: boston_service_request_csv.download_csv_file_url 2022-02-01T00:00:00+00:00 [queued]>
[2022-03-24 18:45:46,354] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: boston_service_request_csv.download_csv_file_url 2022-02-01T00:00:00+00:00 [queued]>
[2022-03-24 18:45:46,355] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 18:45:46,356] {taskinstance.py:1043} INFO - Starting attempt 3 of 3
[2022-03-24 18:45:46,358] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 18:45:46,381] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): download_csv_file_url> on 2022-02-01T00:00:00+00:00
[2022-03-24 18:45:46,391] {standard_task_runner.py:52} INFO - Started process 794 to run task
[2022-03-24 18:45:46,402] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'boston_service_request_csv', 'download_csv_file_url', '2022-02-01T00:00:00+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/boston_service_request.py', '--cfg-path', '/tmp/tmpuihrhwib', '--error-file', '/tmp/tmpaa3gp9tm']
[2022-03-24 18:45:46,409] {standard_task_runner.py:77} INFO - Job 27: Subtask download_csv_file_url
[2022-03-24 18:45:46,509] {logging_mixin.py:104} INFO - Running <TaskInstance: boston_service_request_csv.download_csv_file_url 2022-02-01T00:00:00+00:00 [running]> on host 278b2df668d0
[2022-03-24 18:45:46,626] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=boston_service_request_csv
AIRFLOW_CTX_TASK_ID=download_csv_file_url
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-01T00:00:00+00:00
[2022-03-24 18:45:46,634] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-24 18:45:46,637] {bash.py:158} INFO - Running command: curl -sSL https://data.boston.gov/dataset/8048697b-ad64-4bfc-b090-ee00169f2323/resource/f53ebccd-bc61-49f9-83db-625f209c95f5/download/{filename} > /opt/airflow/boston_2022.csv
[2022-03-24 18:45:46,653] {bash.py:169} INFO - Output:
[2022-03-24 18:45:53,306] {bash.py:177} INFO - Command exited with return code 0
[2022-03-24 18:45:53,371] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=boston_service_request_csv, task_id=download_csv_file_url, execution_date=20220201T000000, start_date=20220324T184546, end_date=20220324T184553
[2022-03-24 18:45:53,435] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-24 18:45:53,481] {local_task_job.py:146} INFO - Task exited with return code 0
[2022-03-26 21:24:48,069] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: boston_service_request_csv.download_csv_file_url 2022-02-01T00:00:00+00:00 [queued]>
[2022-03-26 21:24:48,111] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: boston_service_request_csv.download_csv_file_url 2022-02-01T00:00:00+00:00 [queued]>
[2022-03-26 21:24:48,113] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 21:24:48,115] {taskinstance.py:1043} INFO - Starting attempt 3 of 3
[2022-03-26 21:24:48,116] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-26 21:24:48,143] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): download_csv_file_url> on 2022-02-01T00:00:00+00:00
[2022-03-26 21:24:48,153] {standard_task_runner.py:52} INFO - Started process 751 to run task
[2022-03-26 21:24:48,164] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'boston_service_request_csv', 'download_csv_file_url', '2022-02-01T00:00:00+00:00', '--job-id', '62', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/boston_service_request.py', '--cfg-path', '/tmp/tmpxcqslffp', '--error-file', '/tmp/tmphpnattqx']
[2022-03-26 21:24:48,173] {standard_task_runner.py:77} INFO - Job 62: Subtask download_csv_file_url
[2022-03-26 21:24:48,281] {logging_mixin.py:104} INFO - Running <TaskInstance: boston_service_request_csv.download_csv_file_url 2022-02-01T00:00:00+00:00 [running]> on host 5e460e3a8f6b
[2022-03-26 21:24:48,393] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=boston_service_request_csv
AIRFLOW_CTX_TASK_ID=download_csv_file_url
AIRFLOW_CTX_EXECUTION_DATE=2022-02-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-01T00:00:00+00:00
[2022-03-26 21:24:48,400] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-26 21:24:48,405] {bash.py:158} INFO - Running command: curl -sSL https://data.boston.gov/dataset/8048697b-ad64-4bfc-b090-ee00169f2323/resource/f53ebccd-bc61-49f9-83db-625f209c95f5/download/{filename} > /opt/airflow/boston_2022.csv
[2022-03-26 21:24:48,421] {bash.py:169} INFO - Output:
[2022-03-26 21:25:18,569] {local_task_job.py:188} WARNING - State of this instance has been externally set to shutdown. Terminating instance.
[2022-03-26 21:25:18,596] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 751
[2022-03-26 21:25:18,599] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-03-26 21:25:18,604] {bash.py:185} INFO - Sending SIGTERM signal to bash process group
[2022-03-26 21:25:18,647] {taskinstance.py:1455} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 171, in execute
    for raw_line in iter(self.sub_process.stdout.readline, b''):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-03-26 21:25:18,666] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=boston_service_request_csv, task_id=download_csv_file_url, execution_date=20220201T000000, start_date=20220326T212448, end_date=20220326T212518
[2022-03-26 21:25:18,749] {process_utils.py:66} INFO - Process psutil.Process(pid=753, status='terminated', started='21:24:48') (753) terminated with exit code None
[2022-03-26 21:25:18,752] {process_utils.py:66} INFO - Process psutil.Process(pid=751, status='terminated', exitcode=1, started='21:24:47') (751) terminated with exit code 1
[2022-03-26 21:25:18,755] {process_utils.py:66} INFO - Process psutil.Process(pid=756, status='terminated', started='21:24:48') (756) terminated with exit code None
